package varta.deterministic_clasifying_svc.dto;

public enum FlagReason {
    // Velocity
    HIGH_VELOCITY_1H,
    HIGH_VELOCITY_24H,
    HIGH_MERCHANT_SPREAD_1H,
    RAPID_SEQUENTIAL_TRANSACTIONS,
    VELOCITY_SPIKE,

    // Amount
    AMOUNT_Z_SCORE_OUTLIER,
    AMOUNT_RATIO_TO_MEDIAN_SPIKE,
    AMOUNT_EXCEEDS_HISTORICAL_MAX,
    ROUND_NUMBER_AMOUNT,
    MICRO_CHARGE_CARD_TESTING,
    AMOUNT_BELOW_AUTH_THRESHOLD,

    // Time
    NIGHT_TRANSACTION,
    DORMANT_CARD_REACTIVATION,
    NEW_CARD_HIGH_VALUE_FIRST_TX,

    // Entry / Auth
    CARD_NOT_PRESENT,
    CHIP_FALLBACK_TO_MAGSTRIPE,
    NO_AUTH_HIGH_VALUE,
    NO_AUTH_CNP,
    UNAUTHENTICATED_TRANSFER,

    // Response codes
    DECLINED_THEN_APPROVED,
    HIGH_DECLINE_RATE,
    WRONG_PIN_SPIKE,

    // Merchant / Terminal
    HIGH_RISK_MERCHANT_CATEGORY,
    NULL_MERCHANT,
    TERMINAL_ID_MISMATCH,

    // Structuring
    STRUCTURING_SUB_THRESHOLD,
    FAN_OUT_TRANSFER,
    PASS_THROUGH_ACCOUNT,

    // Transfers
    TRANSFER_TO_ABNORMAL_DESTINATION,
    UNAUTHENTICATED_LARGE_TRANSFER,
    RAPID_RELAY_TRANSFER,

    // Composite
    COMPOSITE_SCORE_EXCEEDED,
    IMPOSSIBLE_FIELD_COMBINATION,
    MULTI_AXIS_NIGHT_BURST,
}
